# Generated by Django 4.2.5 on 2023-09-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.IntegerField()),
                ('patientname', models.CharField(max_length=120)),
                ('doctorid', models.IntegerField()),
                ('doctorname', models.CharField(max_length=120)),
                ('datetime', models.DateTimeField()),
                ('type', models.CharField(max_length=80)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MedicalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.IntegerField()),
                ('bloodGroup', models.CharField(max_length=20)),
                ('onGoingMedication', models.TextField(max_length=200)),
                ('chronicDisease', models.TextField(max_length=200)),
                ('knownAllergies', models.TextField(max_length=200)),
                ('familyHistory', models.TextField(max_length=200)),
                ('medicalReportpdf', models.FileField(upload_to='medical_reports/')),
            ],
        ),
        migrations.CreateModel(
            name='Medications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientid', models.IntegerField()),
                ('doctorid', models.IntegerField()),
                ('doctorname', models.CharField(max_length=80)),
                ('medicinename', models.CharField(max_length=80)),
                ('quantity', models.CharField(max_length=80)),
                ('days', models.CharField(max_length=80)),
                ('time', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.IntegerField()),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
