# Generated by Django 4.2.5 on 2023-09-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetails',
            name='medicalReportpdf',
            field=models.FileField(blank=True, null=True, upload_to='medical_reports/'),
        ),
    ]
