# Generated by Django 4.2.5 on 2023-09-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_medicaldetails_medicalreportpdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldetails',
            name='chronicDisease',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='medicaldetails',
            name='familyHistory',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='medicaldetails',
            name='knownAllergies',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='medicaldetails',
            name='onGoingMedication',
            field=models.TextField(max_length=2000),
        ),
    ]
