# Generated by Django 4.2.5 on 2023-09-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_doctor_password_alter_doctor_details_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(default="<module 'datetime' from 'C:\\\\Users\\\\admin\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python310\\\\lib\\\\datetime.py'>", max_length=100),
            preserve_default=False,
        ),
    ]
